<?php

namespace Repository;

use Tigress\DataRepository;

/**
 * Class FormBuilderFieldTypesRepo
 */
class FormBuilderFieldTypesRepo extends DataRepository
{
    /**
     * Initialize the repository
     */
    public function __construct()
    {
        $this->dbName = null;
        $this->primaryKey = ['id'];
        $this->model = 'DefaultModel';
        parent::__construct();

        $this->setFields([
            'id' => [
                'value' => 0,
                'type' => 'int',
            ],
            'input_type' => [
                'value' => '',
                'type' => 'string',
            ],
            'name' => [
                'value' => '',
                'type' => 'string',
            ],
            'naam' => [
                'value' => '',
                'type' => 'string',
            ],
            'nom' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_de' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_fr' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_nl' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_en' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_es' => [
                'value' => '',
                'type' => 'string',
            ],
            'name_it' => [
                'value' => '',
                'type' => 'string',
            ],
        ]);

        $this->setData([
            [
                'id' => 1,
                'input_type' => 'text',
                'name' => 'Text',
                'naam' => 'Tekst',
                'nom' => 'Texte',
                'name_de' => 'Text',
                'name_fr' => 'Texte',
                'name_nl' => 'Tekst',
                'name_en' => 'Text',
                'name_es' => 'Texto',
                'name_it' => 'Testo',
            ],
            [
                'id' => 2,
                'input_type' => 'textarea',
                'name' => 'Text area',
                'naam' => 'Lange tekst',
                'nom' => 'Texte longue',
                'name_de' => 'Textbereich',
                'name_fr' => 'Zone de texte',
                'name_nl' => 'Tekstvak',
                'name_en' => 'Text area',
                'name_es' => 'Área de texto',
                'name_it' => 'Area di testo',
            ],
            [
                'id' => 3,
                'input_type' => 'number',
                'name' => 'Number',
                'naam' => 'Getal',
                'nom' => 'Nombre',
                'name_de' => 'Nummer',
                'name_fr' => 'Nombre',
                'name_nl' => 'Nummer',
                'name_en' => 'Number',
                'name_es' => 'Número',
                'name_it' => 'Numero',
            ],
            [
                'id' => 4,
                'input_type' => 'email',
                'name' => 'Email',
                'naam' => 'E-mail',
                'nom' => 'E-mail',
                'name_de' => 'E-Mail',
                'name_fr' => 'E-mail',
                'name_nl' => 'E-mail',
                'name_en' => 'Email',
                'name_es' => 'Correo electrónico',
                'name_it' => 'E-mail',
            ],
            [
                'id' => 5,
                'input_type' => 'tel',
                'name' => 'Telephone',
                'naam' => 'Telefoon',
                'nom' => 'Téléphone',
                'name_de' => 'Telefon',
                'name_fr' => 'Téléphone',
                'name_nl' => 'Telefoon',
                'name_en' => 'Telephone',
                'name_es' => 'Teléfono',
                'name_it' => 'Telefono',
            ],
            [
                'id' => 16,
                'input_type' => 'url',
                'name' => 'Weblink',
                'naam' => 'Weblink',
                'nom' => 'Lien web',
                'name_de' => 'Weblink',
                'name_fr' => 'Lien web',
                'name_nl' => 'Weblink',
                'name_en' => 'Weblink',
                'name_es' => 'Enlace web',
                'name_it' => 'Collegamento web',
            ],
            [
                'id' => 6,
                'input_type' => 'password',
                'name' => 'Password',
                'naam' => 'Wachtwoord',
                'nom' => 'Mot de passe',
                'name_de' => 'Passwort',
                'name_fr' => 'Mot de passe',
                'name_nl' => 'Wachtwoord',
                'name_en' => 'Password',
                'name_es' => 'Contraseña',
                'name_it' => 'Password',
            ],
            [
                'id' => 7,
                'input_type' => 'select',
                'name' => 'Selection list',
                'naam' => 'Keuzelijst',
                'nom' => 'Liste déroulante',
                'name_de' => 'Auswahlliste',
                'name_fr' => 'Liste de sélection',
                'name_nl' => 'Keuzelijst',
                'name_en' => 'Selection list',
                'name_es' => 'Lista de selección',
                'name_it' => 'Elenco di selezione',
            ],
            [
                'id' => 8,
                'input_type' => 'datetime-local',
                'name' => 'Date + Time',
                'naam' => 'Datum + Tijd',
                'nom' => 'Date + Heure',
                'name_de' => 'Datum + Uhrzeit',
                'name_fr' => 'Date + Heure',
                'name_nl' => 'Datum + Tijd',
                'name_en' => 'Date + Time',
                'name_es' => 'Fecha + Hora',
                'name_it' => 'Data + Ora',
            ],
            [
                'id' => 9,
                'input_type' => 'date',
                'name' => 'Date',
                'naam' => 'Datum',
                'nom' => 'Date',
                'name_de' => 'Datum',
                'name_fr' => 'Date',
                'name_nl' => 'Datum',
                'name_en' => 'Date',
                'name_es' => 'Fecha',
                'name_it' => 'Data',
            ],
            [
                'id' => 18,
                'input_type' => 'month',
                'name' => 'Month',
                'naam' => 'Maand',
                'nom' => 'Mois',
                'name_de' => 'Monat',
                'name_fr' => 'Mois',
                'name_nl' => 'Maand',
                'name_en' => 'Month',
                'name_es' => 'Mes',
                'name_it' => 'Mese',
            ],
            [
                'id' => 19,
                'input_type' => 'week',
                'name' => 'Week',
                'naam' => 'Week',
                'nom' => 'Semaine',
                'name_de' => 'Woche',
                'name_fr' => 'Semaine',
                'name_nl' => 'Week',
                'name_en' => 'Week',
                'name_es' => 'Semana',
                'name_it' => 'Settimana',
            ],
            [
                'id' => 10,
                'input_type' => 'time',
                'name' => 'Time',
                'naam' => 'Tijd',
                'nom' => 'Heure',
                'name_de' => 'Zeit',
                'name_fr' => 'Heure',
                'name_nl' => 'Tijd',
                'name_en' => 'Time',
                'name_es' => 'Hora',
                'name_it' => 'Ora',
            ],
            [
                'id' => 11,
                'input_type' => 'checkbox',
                'name' => 'Checkbox',
                'naam' => 'Selectievakje',
                'nom' => 'Case à cocher',
                'name_de' => 'Kontrollkästchen',
                'name_fr' => 'Case à cocher',
                'name_nl' => 'Selectievakje',
                'name_en' => 'Checkbox',
                'name_es' => 'Casilla de verificación',
                'name_it' => 'Casella di controllo',
            ],
            [
                'id' => 12,
                'input_type' => 'radio',
                'name' => 'Radio button',
                'naam' => 'Keuzerondje',
                'nom' => 'Bouton radio',
                'name_de' => 'Optionsfeld',
                'name_fr' => 'Bouton radio',
                'name_nl' => 'Keuzerondje',
                'name_en' => 'Radio button',
                'name_es' => 'Botón de opción',
                'name_it' => 'Pulsante radio',
            ],
            [
                'id' => 13,
                'input_type' => 'file',
                'name' => 'File upload',
                'naam' => 'Bestand uploaden',
                'nom' => "Téléverser un fichier",
                'name_de' => 'Datei hochladen',
                'name_fr' => 'Téléverser un fichier',
                'name_nl' => 'Bestand uploaden',
                'name_en' => 'File upload',
                'name_es' => 'Subir archivo',
                'name_it' => 'Caricamento file',
            ],
            [
                'id' => 14,
                'input_type' => 'color',
                'name' => 'Color picker',
                'naam' => 'Kleurkiezer',
                'nom' => "Sélecteur de couleur",
                'name_de' => 'Farbwähler',
                'name_fr' => 'Sélecteur de couleur',
                'name_nl' => 'Kleurkiezer',
                'name_en' => 'Color picker',
                'name_es' => 'Selector de color',
                'name_it' => 'Selettore di colore',
            ],
            [
                'id' => 15,
                'input_type' => 'range',
                'name' => 'Range slider',
                'naam' => 'Schaal',
                'nom' => 'Curseur de plage',
                'name_de' => 'Schieberegler',
                'name_fr' => 'Curseur de plage',
                'name_nl' => 'Schaal',
                'name_en' => 'Range slider',
                'name_es' => 'Deslizador de rango',
                'name_it' => 'Slider di intervallo',
            ],
            [
                'id' => 17,
                'input_type' => 'search',
                'name' => 'Search',
                'naam' => 'Zoeken',
                'nom' => 'Recherche',
                'name_de' => 'Suche',
                'name_fr' => 'Recherche',
                'name_nl' => 'Zoeken',
                'name_en' => 'Search',
                'name_es' => 'Buscar',
                'name_it' => 'Ricerca',
            ],
            [
                'id' => 20,
                'input_type' => 'hidden',
                'name' => 'Hidden',
                'naam' => 'Verborgen veld',
                'nom' => 'Champ caché',
                'name_de' => 'Verstecktes Feld',
                'name_fr' => 'Champ caché',
                'name_nl' => 'Verborgen veld',
                'name_en' => 'Hidden',
                'name_es' => 'Oculto',
                'name_it' => 'Nascosto',
            ],
            [
                'id' => 100,
                'input_type' => 'hr',
                'name' => 'Layout: Horizontal line',
                'naam' => 'Indeling: Horizontale lijn',
                'nom' => 'Disposition : Ligne horizontale',
                'name_de' => 'Layout: Horizontale Linie',
                'name_fr' => 'Disposition : Ligne horizontale',
                'name_nl' => 'Indeling: Horizontale lijn',
                'name_en' => 'Layout: Horizontal line',
                'name_es' => 'Diseño: Línea horizontal',
                'name_it' => 'Layout: Linea orizzontale',
            ],
            [
                'id' => 101,
                'input_type' => 'p',
                'name' => 'Layout: Text section',
                'naam' => 'Indeling: Tekstsectie',
                'nom' => 'Disposition : Section de texte',
                'name_de' => 'Layout: Textabschnitt',
                'name_fr' => 'Disposition : Section de texte',
                'name_nl' => 'Indeling: Tekstsectie',
                'name_en' => 'Layout: Text section',
                'name_es' => 'Diseño: Sección de texto',
                'name_it' => 'Layout: Sezione di testo',
            ],
        ]);
    }

    /**
     * Get the input type by ID.
     *
     * @param int $id
     * @return string
     */
    public function getInputType(int $id): string
    {
        return $this->get($id)->input_type ?? false;
    }
}